# Generated by Django 3.2.7 on 2021-09-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_not_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
