# Generated by Django 3.2.7 on 2021-09-30 18:28

from django.db import migrations


def modify_currency_name(apps, schema_editor):

    Currency = apps.get_model('item', 'Currency')
    for currency in Currency.objects.all():
        currency.name += "'s"
        currency.save()


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210915_0746'),
    ]

    operations = [
        migrations.RunPython(modify_currency_name),
    ]
