version: "3.3"

services:
  backend:
    container_name: djangotrading_container
    build: .
    volumes:
      - ./:/opt/djangoTrading/
    ports:
      - '8000'
    depends_on:
      - postgres
      - redis
    environment:
      SERVICE: backend
  scheduler:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      SERVICE: beat
      CELERY_BROKER: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: djangoTrading.settings
  worker1:
    build: .
    depends_on:
      - postgres
      - redis
      - scheduler
    environment:
      SERVICE: worker
      CELERY_BROKER: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: djangoTrading.settings
      QUEUES: "celery,user"
      C_FORCE_ROOT: 1
  postgres:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading
    ports:
      - '5432'
  redis:
    container_name: redis_container
    image: redis
    ports:
      - '6379'
  nginx:
    container_name: nginx_container
    image: nginx
    depends_on:
      - backend
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/static
    ports:
      - '80:80'