version: "3.3"

services:
  backend:
    container_name: djangotrading_container
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading
    ports:
      - '5432:5432'
  redis:
    container_name: redis_container
    image: redis
    ports:
      - '6379:6379'