version: "3.3"

services:
  backend:
    container_name: djangotrading_container
    build: .
    volumes:
      - ./:/opt/djangoTrading/
    ports:
      - '8000'
    depends_on:
      - postgres
      - redis
    environment:
      SERVICE: backend
  scheduler:
    container_name: scheduler
    build: .
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./:/opt/djangoTrading/
    environment:
      SERVICE: beat
  worker:
    container_name: worker
    build: .
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - scheduler
    volumes:
      - ./:/opt/djangoTrading/
    environment:
      SERVICE: worker
      QUEUES: "celery,user"
      C_FORCE_ROOT: 1
  postgres:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading
    ports:
      - '5432'
  redis:
    container_name: redis_container
    image: redis
    ports:
      - '6379'
  rabbitmq:
    container_name: rabitmq_container
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - '5672'
      - '15672'
  nginx:
    container_name: nginx_container
    image: nginx
    depends_on:
      - backend
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/static
    ports:
      - '80:80'