# Generated by Django 3.2.7 on 2021-09-21 11:07

import django.core.validators
from django.db import migrations, models
import trading.enums


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20210915_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.CharField(choices=[('Sale', trading.enums.OrderType['SALE']), ('Purchase', trading.enums.OrderType['PURCHASE'])], max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
