# Generated by Django 3.2.7 on 2021-10-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210930_1828'),
        ('trading', '0003_auto_20210921_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='item.item'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyer_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_trade', to='trading.offer'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_trade', to='trading.offer'),
        ),
    ]
