# Generated by Django 3.2.7 on 2021-10-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20211008_0819'),
        ('trading', '0004_auto_20211005_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='item.item'),
        ),
    ]
