# Generated by Django 3.2.7 on 2021-09-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210921_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='banned',
        ),
    ]
